{
    "name": "Wex Knowledge",
    "version": "18.0.1.0.0",
    "summary": "Base de conocimiento interna moderna para Odoo 18 Community",
    "category": "Knowledge",
    "author": "Wexplay",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "web_editor",
        "product",
        "purchase",
        "repair",
        "sale",
        "stock",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/knowledge_dashboard_views.xml",
        "views/knowledge_article_views.xml",
        "views/knowledge_category_views.xml",
        "views/knowledge_tag_views.xml",
        "views/repair_order_views.xml",
        "views/purchase_order_views.xml",
        "views/stock_picking_views.xml",
        "views/sale_order_views.xml",
        "views/product_template_views.xml",
        "views/knowledge_menu.xml",
    ],
    "images": [
        "static/description/icon.png",
    ],
    "assets": {
        "web.assets_backend": [
            "wex_knowledge/static/src/js/knowledge_client_actions.js",
            "wex_knowledge/static/src/js/knowledge_icon_picker_field.js",
            "wex_knowledge/static/src/xml/knowledge_client_actions.xml",
            "wex_knowledge/static/src/xml/knowledge_icon_picker_field.xml",
            "wex_knowledge/static/src/scss/knowledge.scss",
        ],
    },
    "installable": True,
    "application": True,
}
