from . import knowledge_article
from . import knowledge_article_history
from . import knowledge_article_link
from . import knowledge_category
from . import knowledge_tag
from . import repair_order
from . import purchase_order
from . import stock_picking
from . import sale_order
from . import product_template
