from . import res_partner
from . import it_service_type
from . import it_software_type
from . import it_network_type
from . import it_coverage
from . import it_asset
from . import it_asset_review
from . import it_service
from . import it_software
from . import it_network
from . import it_credential
from . import it_maintenance_template
from . import it_maintenance_visit
