{
    "name": "Wexplay - Despieces",
    "version": "18.0.1.0.0",
    "summary": "Gestion de despieces y creacion controlada de repuestos",
    "category": "Wexplay",
    "author": "Wexplay",
    "license": "LGPL-3",
    "depends": [
        "base",
        "product",
        "stock",
        "mail",
        "web",
        "wexplay_repair",
        "wex_product_codes",
    ],
    "data": [
        "security/wex_teardown_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/stock_location_data.xml",
        "data/product_tag_data.xml",
        "views/wex_teardown_reject_wizard_views.xml",
        "views/wex_teardown_menus.xml",
        "views/wex_teardown_component_type_views.xml",
        "views/wex_teardown_category_rule_views.xml",
        "views/wex_teardown_name_rule_views.xml",
        "views/wex_teardown_template_views.xml",
        "views/wex_teardown_batch_views.xml",
        "views/product_template_views.xml",
        "views/res_company_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "wex_teardown/static/src/js/duplicate_check_widget.js",
            "wex_teardown/static/src/js/notebook_focus_widget.js",
            "wex_teardown/static/src/js/pieces_operational_widget.js",
            "wex_teardown/static/src/js/data_completion_widget.js",
            "wex_teardown/static/src/xml/duplicate_check_widget.xml",
            "wex_teardown/static/src/xml/notebook_focus_widget.xml",
            "wex_teardown/static/src/xml/pieces_operational_widget.xml",
            "wex_teardown/static/src/xml/data_completion_widget.xml",
            "wex_teardown/static/src/scss/duplicate_check_widget.scss",
            "wex_teardown/static/src/scss/pieces_operational_widget.scss",
            "wex_teardown/static/src/scss/data_completion_widget.scss",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
